website:
  page-navigation: true
  title: "Betsy Cohen"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: about.qmd
        text: About
  page-footer:
    left: "Este sitio está hecho con 💜 y [Quarto](https://quarto.org/)"
    right:
      - icon: github
        href: https://github.com/BetsyCohen/
      - icon: linkedin
        href: https://www.linkedin.com/in/betsabe1984/
      - icon: envelope
        href: mailto:betsabecohen@gmail.com

      

format:
  html:
    smooth-scroll: true
    theme: cosmo
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/betsycohen.github.io\/**'
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

editor: visual

execute:
  freeze: true





